// app/templates/react/src/app.js
import React, { Component } from 'react'
import devery from './devery'
import LoadData from './LoadData'
import PostData from './PostData';

export default class extends Component {
    constructor(props, context) {
        super(props, context);

        this.state = {
            account: '',
            checkBrandAddr: '',
            checkProductAddr: '',
            appAddr: null,
        }
    }

    componentDidMount() {
        if (!window.web3) return;

        if (window.web3.eth && window.web3.eth.accounts) {
            this.updateAccount(window.web3.eth.accounts[0]);
        }

        if (window.web3.currentProvider) {
            window.web3.currentProvider.isMetaMask && window.web3.currentProvider.enable();
            window.web3.currentProvider.publicConfigStore
                .on('update', ({selectedAddress}) => this.updateAccount(selectedAddress));
        }
    }

    updateAccount = account => {
        if (this.state.account === account) return;
        this.setState({account})
    };

    handleBrandAddrChange = ({ target: { value } }) => {
        this.setState({ checkBrandAddr: value })
    };

    handleProductAddrChange = ({ target: { value } }) => {
        this.setState({ checkProductAddr: value })
    };

    handleAppAccountChange = ({ target: { value } }) => {
        this.setState({ appAddr: value })
    };

    // All devery methods used in this example can be found at https://devery.github.io/deveryjs/

    getBrand = async () => {
        const Brand = await devery.getBrand(this.state.checkBrandAddr);
        if (!Brand.active) return Promise.reject('No active brand');
        return Promise.resolve(Brand)
    };

    getProduct = async () => {
        const Product = await devery.getProduct(this.state.checkProductAddr);
        if (!Product.active) return Promise.reject('No product');
        return Promise.resolve(Product)
    };

    handleGetAppAccounts = () => {
        return devery.appAccountsPaginated(0, 10)
    };

    handleGetApp = async () => {
        return devery.getApp(this.state.appAddr)
    };

    handleGetBrandAccounts = () => {
        return devery.brandAccountsPaginated(0, 10)
    };

    handleGetProductAccounts = () => {
        return devery.productAccountsPaginated(0, 10)
    };

    handleAddApp = async (data) => {
        try {
            await devery.addApp(data, this.state.account, 0);
        } catch (e) {
            if (e.message.indexOf('User denied')) {
                console.log('The user denied the transaction')
            }
        }
    };

    handleAddBrand = async (data) => {
        try {
            await devery.addBrand(this.state.account, data);
        } catch (e) {
            if (e.message.indexOf('User denied')) {
                console.log('The user denied the transaction')
            }
        }
    };

    handleAddProduct = async (data) => {
        try {
            await devery.addProduct(this.state.account, data, 'batch 001', new Date().getFullYear(), 'Unknown place');
        } catch (e) {
            if (e.message.indexOf('User denied')) {
                console.log('The user denied the transaction')
            }
        }
    };

    render() {
        const {
            account
        } = this.state;

        return (
            <div className="Explorer">
                <h1>Devery Explorer</h1>

                <h3>User Account:</h3>
                {
                    !account
                        ? <span>Please sign in to MetaMask</span>
                        : <span>{account}</span>
                }

                <h2>APP INFO</h2>
                <fieldset>
                    <h3>Get App Accounts:</h3>

                    <LoadData
                        buttonMessage='Get App Accounts'
                        loadDataFunc={this.handleGetAppAccounts}
                    />
                </fieldset>

                <fieldset>
                    <h3>Get App:</h3>
                    <label>
                        <span>App Info: active, appAccount, appName, fee, feeAccount</span>
                        <input type="text" placeholder="App Address" onChange={this.handleAppAccountChange}/>
                    </label>
                    {
                        !this.state.appAddr
                            ? (<span>Please insert App address first!</span>)
                            : (<LoadData
                                buttonMessage='Get App'
                                loadDataFunc={this.handleGetApp}
                            />)
                    }
                </fieldset>

                <fieldset>
                    <h3>Add App:</h3>
                    {
                        !this.state.account
                            ? (<span>Login with metamask first!</span>)
                            : (<PostData
                                postDataFunc={this.handleAddApp}
                            />)
                    }
                </fieldset>

                <h2>BRAND INFO</h2>

                <fieldset>
                    <h3>Get Brand Accounts:</h3>
                    <p>This gets ALL brand accounts. i.e. Not just for your app.</p>

                    <LoadData
                        buttonMessage='Get Brand Accounts'
                        loadDataFunc={this.handleGetBrandAccounts}
                    />
                </fieldset>

                <fieldset>
                    <h3>Get Brand Info:</h3>
                    <label>
                        <span>Brand Info: brandAccount, appAccount, brandName, active</span>
                        <input type="text" placeholder="Enter Brand Address" onChange={this.handleBrandAddrChange}/>
                    </label>

                    {
                        !this.state.checkBrandAddr
                            ? (<span>Please insert Brand address first!</span>)
                            : (<LoadData
                                buttonMessage='Get Brand Info'
                                loadDataFunc={this.getBrand}
                            />)
                    }
                </fieldset>

                <fieldset>
                    <h3>Add Brand:</h3>
                    {
                        !this.state.account
                            ? (<span>Login with metamask first!</span>)
                            : (<PostData
                                postDataFunc={this.handleAddBrand}
                            />)
                    }
                </fieldset>

                <h2>PRODUCT INFO</h2>

                <fieldset>
                    <h3>Get Product Accounts:</h3>
                    <p>This gets ALL product accounts. i.e. Not just for your app/brand.</p>

                    <LoadData
                        buttonMessage='Get Product Accounts'
                        loadDataFunc={this.handleGetProductAccounts}
                    />
                </fieldset>

                <fieldset>
                    <h3>Get Product Info:</h3>
                    <label>
                        <span>Product Info: productAccount, brandAccount, description, details, year, origin, active</span>
                        <input type="text" placeholder="Enter A Product Address" onChange={this.handleProductAddrChange}/>
                    </label>

                    {
                        !this.state.checkProductAddr
                            ? (<span>Please insert Product address first!</span>)
                            : (<LoadData
                                buttonMessage='Get Product Info'
                                loadDataFunc={this.getProduct}
                            />)
                    }
                </fieldset>

                <fieldset>
                    <h3>Add Product:</h3>
                    {
                        !this.state.account
                            ? (<span>Login with metamask first!</span>)
                            : (<PostData
                                postDataFunc={this.handleAddProduct}
                            />)
                    }
                </fieldset>
            </div>
        )
    }
}

// app/templates/vue/src/App.vue
<template>
    <div class="Explorer">
        <h1>Devery Explorer</h1>
        <h3>User Account:</h3>
        <span v-if="!account">Please sign in to MetaMask</span>
        <span v-else>{{account}}</span>

        <h2>APP INFO</h2>
        <fieldset>
            <h3>Get App Accounts:</h3>

            <LoadData
                    v-bind:loadDataFunc="handleGetAppAccounts"
                    buttonMessage='Get App Accounts'
            />
        </fieldset>

        <fieldset>
            <h3>Get App:</h3>

            <label>
                <span>App Info: active, appAccount, appName, fee, feeAccount</span>
                <input type="text" placeholder="App Address" v-model="appAddr"/>
            </label>

            <span v-if="!appAddr">Please insert App address first!</span>
            <LoadData
                    v-else
                    v-bind:loadDataFunc="handleGetApp"
                    buttonMessage='Get App Info'
            />
        </fieldset>

        <fieldset>
            <h3>Add App:</h3>

            <span v-if="!account">Login with metamask first!</span>
            <PostData
                    v-else
                    v-bind:postDataFunc="addApp"
            />
        </fieldset>

        <h2>BRAND INFO</h2>

        <fieldset>
            <h3>Get Brand Accounts:</h3>
            <p>This gets ALL brand accounts. i.e. Not just for your app.</p>

            <LoadData
                    v-bind:loadDataFunc="handleGetBrandAccounts"
                    buttonMessage='Get Brand Accounts'
            />
        </fieldset>

        <fieldset>
            <h3>Get Brand Info:</h3>
            <label>
                <span>Brand Info: brandAccount, appAccount, brandName, active</span>
                <input type="text" placeholder="Enter Brand Address" v-model="checkBrandAddr"/>
            </label>

            <span v-if="!checkBrandAddr">Please insert Brand address first!</span>
            <LoadData
                    v-else
                    v-bind:loadDataFunc="getBrand"
                    buttonMessage='Get Brand Info'
            />
        </fieldset>

        <fieldset>
            <h3>Add Brand:</h3>

            <span v-if="!account">Login with metamask first!</span>
            <PostData
                    v-else
                    v-bind:postDataFunc="addBrand"
            />
        </fieldset>

        <h2>PRODUCT INFO</h2>

        <fieldset>
            <h3>Get Product Accounts:</h3>
            <p>This gets ALL product accounts. i.e. Not just for your app/brand.</p>

            <LoadData
                    v-bind:loadDataFunc="handleGetProductAccounts"
                    buttonMessage='Get Product Accounts'
            />
        </fieldset>

        <fieldset>
            <h3>Get Product Info:</h3>

            <label>
                <span>Product Info: productAccount, brandAccount, description, details, year, origin, active</span>
                <input type="text" placeholder="Enter A Product Address" v-model="checkProductAddr"/>
            </label>

            <span v-if="!checkProductAddr">Please insert Product address first!</span>
            <LoadData
                    v-else
                    v-bind:loadDataFunc="getProduct"
                    buttonMessage='Get Product Info'
            />
        </fieldset>

        <fieldset>
            <h3>Add Product:</h3>

            <span v-if="!account">Login with metamask first!</span>
            <PostData
                    v-else
                    v-bind:postDataFunc="addProduct"
            />
        </fieldset>
    </div>
</template>

<script>
    import devery from './devery'
    import LoadData from './LoadData.vue'
    import PostData from './PostData.vue'

    export default {
        components: {
            LoadData,
            PostData
        },
        data() {
            return {
                account: '',
                appAddr: '',
                checkBrandAddr: '',
                checkProductAddr: '',
            }
        },
        created() {
            if (!window.web3) return;

            if (window.web3.eth && window.web3.eth.accounts) {
                this.updateAccount(window.web3.eth.accounts[0]);
            }

            if (window.web3.currentProvider) {
                window.web3.currentProvider.isMetaMask && window.web3.currentProvider.enable();
                window.web3.currentProvider.publicConfigStore
                    .on('update', ({selectedAddress}) => this.updateAccount(selectedAddress));
            }
        },
        methods: {
            updateAccount(account) {
                if (this.account === account) return;
                this.account = account;
            },

            // All devery methods used in this example can be found at https://devery.github.io/deveryjs/

            handleGetAppAccounts() {
                return devery.appAccountsPaginated()
            },
            handleGetApp() {
                return devery.getApp(this.appAddr)
            },
            handleGetBrandAccounts() {
                return devery.brandAccountsPaginated()
            },
            handleGetProductAccounts() {
                return devery.productAccountsPaginated()
            },
            async getBrand() {
                const Brand = await devery.getBrand(this.checkBrandAddr);
                if (!Brand.active) return Promise.reject('No active brand');
                return Promise.resolve(Brand)
            },
            async getProduct() {
                const Product = await devery.getProduct(this.checkProductAddr);
                if (!Product.active) return Promise.reject('No product');
                return Promise.resolve(Product)
            },
            async addApp(data) {
                try {
                    await devery.addApp(data, this.account, 0);
                } catch (e) {
                    if (e.message.indexOf('User denied')) {
                        console.log('The user denied the transaction')
                    }
                }
            },
            async addBrand(data) {
                try {
                    await devery.addBrand(this.account, data)
                } catch (e) {
                    if (e.message.indexOf('User denied')) {
                        console.log('The user denied the transaction')
                    }
                }
            },
            async addProduct(data) {
                try {
                    await devery.addProduct(this.account, data, 'batch 001', new Date().getFullYear(), 'Unknown place')
                } catch (e) {
                    if (e.message.indexOf('User denied')) {
                        console.log('The user denied the transaction')
                    }
                }
            }
        }
    }
</script>

<style>
    body {
        margin: 0;
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen",
        "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue",
        sans-serif;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
    }

    code {
        font-family: source-code-pro, Menlo, Monaco, Consolas, "Courier New",
        monospace;
    }

    .Explorer fieldset {
        margin-bottom: 20px;
        border: none;
    }

    .Explorer pre {
        word-break: break-word;
        white-space: pre-line;
        background: #ebebeb;
        padding: 16px;
        overflow-wrap: break-word;
    }

    .Explorer span {
        display: block;
        margin: 12px 0;
    }

    .Explorer fieldset > span {
        padding: 16px;
        background: #f9f9f9;
    }

    .Explorer input {
        font-size: 16px;
        padding: 2px 4px;
    }

    .Explorer {
        width: 80%;
        margin: 0 auto;
    }
</style>
