// app/templates/vue/src/LoadData.vue
<template>
    <div>
        <pre>{{children}}</pre>
        <br/>
        <button type="button" v-on:click="handleLoadData">{{buttonMessage}}</button>
    </div>
</template>

<script>
    export default {
        data() {
            return {
                isLoading: false,
                children: 'Not loaded',
            }
        },
        props: {
            loadDataFunc: {
                type: Function
            },
            buttonMessage: {
                type: String,
                default: 'Load',
            },
        },
        methods: {
            async handleLoadData() {
                let children;

                this.isLoading = true;
                this.children = 'Loading';

                try {
                    children = JSON.stringify(await this.loadDataFunc());
                } catch (e) {
                    console.error(e);

                    children = 'Something went wrong';
                }

                this.children = children;
                this.isLoading = false;
            }
        }
    }
</script>

// app/templates/react/src/LoadData.js
import React, { Component, Fragment } from 'react'

export default class extends Component {
    constructor(props, context) {
        super(props, context);

        this.state = {
            isLoading: false,
            children: 'Not loaded'
        }
    }

    render() {
        const {
            props: { buttonMessage = 'Load' },
            state: { children }
        } = this;

        return (
            <Fragment>
                <pre>{children}</pre>
                <br/>
                <button type="button" onClick={this.handleLoadData}>{buttonMessage}</button>
            </Fragment>
        )
    }

    handleLoadData = async () => {
        const wrong = 'Something went wrong';
        let children;

        this.setState({ isLoading: true, children: 'Loading' });

        try {
            children = JSON.stringify(await this.props.loadDataFunc());
        } catch (e) {
            console.error(e);
            children = wrong
        }
        this.setState({ isLoading: false, children })
    }
}
